# Generated by Django 5.0 on 2023-12-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_control_name'),
        ('modal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='model_id',
        ),
        migrations.AddField(
            model_name='control',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='modal.modal'),
        ),
    ]
