# Generated by Django 5.0 on 2023-12-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0001_initial'),
        ('output', '0006_remove_output_model_id_output_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='model',
        ),
        migrations.AddField(
            model_name='output',
            name='model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modal.modal'),
        ),
    ]
